@extends('layout.template')

@section('content')
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No</th>
                <th>Nama</th>
                <th>NIM</th>
                <th>Kelas</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>Atika</td>
                <td>23</td>
                <td>A</td>
            </tr>
            <tr>
                <td>2</td>
                <td>Fay</td>
                <td>23</td>
                <td>A</td>
            </tr>
            <tr>
                <td>3</td>
                <td>Galuh</td>
                <td>23</td>
                <td>A</td>
            </tr>
            <tr>
                <td>4</td>
                <td>Meiva</td>
                <td>23</td>
                <td>A</td>
            </tr>
        </tbody>
    </table>
@endsection

